version: '3'

services:
  video-player:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./videos:/app/videos
      - ./config:/app/config
    restart: unless-stopped 