server:
  ip: "0.0.0.0"
  port: "8080"
video:
  scan_dirs:
    - "./videos"
  supported_formats:
    - ".mp4"
    - ".mkv"
    - ".avi"
  random_play: false
access:
  enable_code: true
  access_code: "123456" 